version: '3.8'

services:
  db:
    image: postgres:16
    container_name: agenda-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: agenda_db
      POSTGRES_INITDB_ARGS: "-E UTF8 --lc-collate=C.UTF-8 --lc-ctype=C.UTF-8"
    command: ["postgres", "-c", "shared_preload_libraries=uuid-ossp"]
    ports:
       - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./internal/config/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db_data: